/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storage;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class MainStorageJFrame extends javax.swing.JFrame {
    // Δήλωση αντικειμενου σύνδεσης
    public static Connection con;
    

    /**
     * Creates new form MainStorageJFrame
     */
    public MainStorageJFrame() {
        initComponents();
    }
    
    public void exitAction() {
        this.dispose();
    }
    
     /**
     * Συνδεση με τη βαση δεδομενων
     */
    public void connectAction() {
        UserConnectJDialog cDlg= new UserConnectJDialog(this, true);
        
        cDlg.setVisible(true);

        if ( cDlg.getUserChoosedOkFlag() == false) {
            return;
        }
        
        // Ακολουθεί κωδικας Συνδεσης με τη Βαση Δεδομένων!
        
        try {
            // Φορτωσε το driver της Oracle
            Class.forName("oracle.jdbc.driver.OracleDriver");

            con = DriverManager.getConnection(cDlg.getConnectString(), cDlg.getUsername(), cDlg.getPassword());

            // Έχω συνδεθεί!
            jConnectItem.setEnabled(false);
            
           // JOptionPane.showMessageDialog( this , "Connected Success fully!" );
            
        } 
        catch (java.sql.SQLException e) {
           JOptionPane.showMessageDialog( this , e.getMessage() );
        } 
        catch (Exception e) {
           JOptionPane.showMessageDialog( this , e.getMessage() );
        }

        //
        setActionsStatus();
    }
     /*
        Αποσύνδεση απο τη βάση δεδομενων
    */
    public void disconnectAction() {
        try {

            con.close();
            
            jConnectItem.setEnabled(true);
            
        } 
        catch (java.sql.SQLException e) {
           JOptionPane.showMessageDialog( this , e.getMessage() );
        } 
        
        setActionsStatus();
    }
    
    /*
    Προγραμματίζει ποιες απο τις επιλογες των μενου θα ειναι ενεργες ή οχι
    */
    public void setActionsStatus() {
        
        if (jConnectItem.isEnabled() == false) {
            //Όταν ειναι συνδεδεμενος
            jDisconnectItem.setEnabled(true);
            jEditMenu.setEnabled(true);
            jViewMenu.setEnabled(true);
        }
        else {
            //Όταν δεν ειναι συνδεδεμενος
            jDisconnectItem.setEnabled(false);
            jEditMenu.setEnabled(false);
            jViewMenu.setEnabled(false);            
        }
    }
    
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jFileMenu = new javax.swing.JMenu();
        jConnectItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jDisconnectItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jExitItem = new javax.swing.JMenuItem();
        jEditMenu = new javax.swing.JMenu();
        jViewMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileMenu.setText("File");

        jConnectItem.setText("Connect");
        jConnectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jConnectItem);
        jFileMenu.add(jSeparator1);

        jDisconnectItem.setText("Disconnect");
        jDisconnectItem.setEnabled(false);
        jDisconnectItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDisconnectItemActionPerformed(evt);
            }
        });
        jFileMenu.add(jDisconnectItem);
        jFileMenu.add(jSeparator2);

        jExitItem.setText("Exit");
        jFileMenu.add(jExitItem);

        jMenuBar1.add(jFileMenu);

        jEditMenu.setText("Edit");
        jEditMenu.setEnabled(false);
        jMenuBar1.add(jEditMenu);

        jViewMenu.setText("View");
        jViewMenu.setEnabled(false);
        jMenuBar1.add(jViewMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDisconnectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDisconnectItemActionPerformed
        // TODO add your handling code here:
        disconnectAction();
    }//GEN-LAST:event_jDisconnectItemActionPerformed

    private void jConnectItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectItemActionPerformed
        // TODO add your handling code here:
        connectAction();
    }//GEN-LAST:event_jConnectItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainStorageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainStorageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainStorageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStorageJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainStorageJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jConnectItem;
    private javax.swing.JMenuItem jDisconnectItem;
    private javax.swing.JMenu jEditMenu;
    private javax.swing.JMenuItem jExitItem;
    private javax.swing.JMenu jFileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu jViewMenu;
    // End of variables declaration//GEN-END:variables
}
