/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package storage;

/**
 *
 * @author User
 */
public class UserConnectJDialog extends javax.swing.JDialog {
    
    // Μεταβλητη flag
    private boolean userChoosedOkFlag;
    
    
    
    

    /**
     * Creates new form UserConnectJDialog
     */
    public UserConnectJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        userChoosedOkFlag=false;
        
        
        
       
        
        initComponents();
    }
       
    /* Getters */

    public boolean getUserChoosedOkFlag() {
        return userChoosedOkFlag;
    }
    
    
    
    
    
    
    /**
     * Επιστρέφει το username που εχει γραψει ο χρήστης
     * @return 
     */
    public String getUsername() {
        return jUsernameTxt.getText();
    }
    /**
     * Επιστρέφει το password που εχει γραψει ο χρήστης
     * @return 
     */    
    public String getPassword() {
        return jPasswordTxt.getText();        
    }
    
    /**
     * Επιστρέφει το Connect String που εχει γραψει ο χρήστης
     * @return 
     */    
    public String getConnectString() {
        return jConnectStringTxt.getText();        
    }
    
    public void okAction() {
        userChoosedOkFlag=true;
        dispose();
    }
    
    public void cancelAction() {
        userChoosedOkFlag=false;
        dispose();        
    }
    
    
    
    
    
    
     /**
     * Κανε το Ok Button Enable αν ολα τα text fields έχουν μεσα τιμη
     * αλλιως κανε το ok button disable
     */
    
    public void hideEnableCheck() {
        if (
            (jConnectStringTxt.getText().length() > 10)    
                ) 
        {
            jHideBtn.setEnabled(true);
        } 
        else {
            jHideBtn.setEnabled(false);
        }
    }
    
    
    public void okEnableCheck() {
        if (       (jUsernameTxt.getText().length() > 0)
                && (jPasswordTxt.getText().length() > 0)
                && (jConnectStringTxt.getText().length() > 0)) 
        {
            jOkBtn.setEnabled(true);
        } 
        else {
            jOkBtn.setEnabled(false);
        }
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernamejLabel = new javax.swing.JLabel();
        PasswordjLabel = new javax.swing.JLabel();
        jUsernameTxt = new javax.swing.JTextField();
        jPasswordTxt = new javax.swing.JTextField();
        ConnectStringjLabel = new javax.swing.JLabel();
        jConnectStringTxt = new javax.swing.JTextField();
        jOkBtn = new javax.swing.JButton();
        jCancelBtn = new javax.swing.JButton();
        jHideBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        UsernamejLabel.setText("Username");

        PasswordjLabel.setText("Password");

        jUsernameTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jUsernameTxtCaretUpdate(evt);
            }
        });
        jUsernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameTxtActionPerformed(evt);
            }
        });

        jPasswordTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordTxtCaretUpdate(evt);
            }
        });

        ConnectStringjLabel.setText("Connect String");

        jConnectStringTxt.setText("jdbc:oracle:thin:@127.0.0.1:1521:xe");
        jConnectStringTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jConnectStringTxtCaretUpdate(evt);
            }
        });
        jConnectStringTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectStringTxtActionPerformed(evt);
            }
        });

        jOkBtn.setText("Ok");
        jOkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOkBtnActionPerformed(evt);
            }
        });

        jCancelBtn.setText("Cancel");
        jCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelBtnActionPerformed(evt);
            }
        });

        jHideBtn.setText("Hide");
        jHideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHideBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCancelBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jOkBtn)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UsernamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUsernameTxt))
                        .addGap(173, 187, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPasswordTxt)
                            .addComponent(PasswordjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jConnectStringTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jHideBtn))
                            .addComponent(ConnectStringjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 65, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernamejLabel)
                    .addComponent(PasswordjLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(ConnectStringjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConnectStringTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jHideBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOkBtn)
                    .addComponent(jCancelBtn))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOkBtnActionPerformed
        // TODO add your handling code here:
        okAction();
    }//GEN-LAST:event_jOkBtnActionPerformed

    private void jConnectStringTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectStringTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConnectStringTxtActionPerformed

    private void jCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelBtnActionPerformed
        // TODO add your handling code here:
        cancelAction();
    }//GEN-LAST:event_jCancelBtnActionPerformed

    private void jUsernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameTxtActionPerformed

    private void jUsernameTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jUsernameTxtCaretUpdate
        // TODO add your handling code here:
        okEnableCheck();
    }//GEN-LAST:event_jUsernameTxtCaretUpdate

    private void jPasswordTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordTxtCaretUpdate
        // TODO add your handling code here:
        okEnableCheck();
    }//GEN-LAST:event_jPasswordTxtCaretUpdate

    private void jConnectStringTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jConnectStringTxtCaretUpdate
        // TODO add your handling code here:
        okEnableCheck();
        hideEnableCheck();
    }//GEN-LAST:event_jConnectStringTxtCaretUpdate

    private void jHideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHideBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jHideBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserConnectJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserConnectJDialog dialog = new UserConnectJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConnectStringjLabel;
    private javax.swing.JLabel PasswordjLabel;
    private javax.swing.JLabel UsernamejLabel;
    private javax.swing.JButton jCancelBtn;
    private javax.swing.JTextField jConnectStringTxt;
    private javax.swing.JButton jHideBtn;
    private javax.swing.JButton jOkBtn;
    private javax.swing.JTextField jPasswordTxt;
    private javax.swing.JTextField jUsernameTxt;
    // End of variables declaration//GEN-END:variables
}
